# CREATE USER
POST http://localhost:3000/user HTTP/2.0
Content-Type: application/json

{
  "name": "Breno"
}

###
# RETURN ALL USERS
GET http://localhost:3000/user HTTP/2.0

###
# RETURN USER BY ID
GET http://localhost:3000/user/2 HTTP/2.0

###
# UPDATE USER
PUT http://localhost:3000/user HTTP/2.0
Content-Type: application/json

{
  "id": 4,
  "name": "Aparecido Freitas"
}

###
# RETURN ALL USERS
GET http://localhost:3000/user HTTP/2.0


###
# DELETE USER

DELETE http://localhost:3000/user?id=3 HTTP/2.0
