# CREATE WALLET
POST http://localhost:3000/wallet HTTP/2.0
Content-Type: application/json

{
  "idUser": 1,
  "name": "My New Wallet 2"
}

###

# RETURN ALL WALLETS FROM USER
GET http://localhost:3000/wallet/GetByUserId/1 HTTP/2.0

###