# CREATE WALLET
POST http://localhost:3000/wallet HTTP/2.0
Content-Type: application/json

{
  "idUser": 5,
  "name": "Carteira a ser destruida"
}

###

# RETURN ALL WALLETS FROM USER
GET http://localhost:3000/wallet/GetByUserId/5 HTTP/2.0

###

# RETURN WALLET BY ID
GET http://localhost:3000/wallet?id=9509f40e-a3e4-4613-be2a-e06b4cfed97d HTTP/2.0


###
# UPDATE WALLET
PUT http://localhost:3000/wallet HTTP/2.0
Content-Type: application/json

{
  "id": "80065f7e-4b2b-11ec-81d3-0242ac130003",
  "name": "Minha Carteira Renomeada"
}

###
# DELETE WALLET
DELETE http://localhost:3000/wallet?id=10bbc2a6-0296-4900-894a-74b26acec279 HTTP/2.0
