# CREATE WALLET
POST http://localhost:3000/wallet HTTP/2.0
Content-Type: application/json

{
  "idUser": 1,
  "name": "Carteira a ser destruida"
}

###

# RETURN ALL WALLETS FROM USER
GET http://localhost:3000/wallet/GetByUserId/1 HTTP/2.0

###

# RETURN WALLET BY ID
GET http://localhost:3000/wallet?id=e302c24d-f5b1-4d62-b59b-e761b28023f3 HTTP/2.0


###
# UPDATE WALLET
PUT http://localhost:3000/wallet HTTP/2.0
Content-Type: application/json

{
  "id": "e302c24d-f5b1-4d62-b59b-e761b28023f3",
  "name": "Minha Carteira Renomeada"
}

###
# RETURN WALLET BY ID
GET http://localhost:3000/wallet?id=e302c24d-f5b1-4d62-b59b-e761b28023f3 HTTP/2.0

###
# DELETE WALLET
DELETE http://localhost:3000/wallet?id=10bbc2a6-0296-4900-894a-74b26acec279 HTTP/2.0
